templates/model.ts.njk

Actually if more than one properties has a default value the withDefault function is imported more than once

Import withDefault only once

---

src/__tests__/__snapshots__/gen-api-models.test.ts.snap
src/__tests__/api.yaml
src/__tests__/gen-api-models.test.ts
templates/macros.njk
templates/model.ts.njk

needed to make dictionary types

[#157505713] adds support for additional properties

---

src/__tests__/__snapshots__/gen-api-models.test.ts.snap
src/__tests__/api.yaml
src/__tests__/gen-api-models.test.ts
templates/macros.njk

ref. https://github.com/OAI/OpenAPI-Specification/issues/668

fix: additionalProperties

---

src/__tests__/__snapshots__/gen-api-models.test.ts.snap
src/__tests__/api.yaml
src/__tests__/gen-api-models.test.ts
templates/macros.njk

this fixes a bug when minimum is set to 0

fix: generation of withrangenumbers

---

src/__tests__/__snapshots__/gen-api-models.test.ts.snap
src/__tests__/api.yaml
src/__tests__/gen-api-models.test.ts
templates/macros.njk

let us use custom types for strings according to the spcified format (and imported module)

feat: custom string formats

---

package.json
src/__tests__/__snapshots__/gen-api-models.test.ts.snap
src/__tests__/api.yaml
src/__tests__/gen-api-models.test.ts
src/gen-api-models.ts
templates/macros.njk

support custom types and type aliases

[#158519397] support custom types

---

src/__tests__/__snapshots__/gen-api-models.test.ts.snap
src/__tests__/api.yaml
templates/macros.njk

Previous code didn't produce valid typescript code for properties of type `object`

Object property names should be properly capitalized

---

src/__tests__/__snapshots__/gen-api-models.test.ts.snap
src/__tests__/api.yaml

- add `multipart/form-data`
- fix`decription` to `description`
- update snapshot 
#93 
#92

Fix yaml file

---

README.md

how the specifications should be to avoid mistakes
This is for Google Summer of Code

how the specifications should be

---

README.md

merges with master so we can automatically merge

Fix support_openapi3 so that it can be automatically merged

---

src/__tests__/__snapshots__/gen-api-models.test.ts.snap
src/gen-api-models/index.ts

This is a variant of #172. Please refer to that for the discussion

variant on generators

---

.prettierrc
src/__tests__/__snapshots__/gen-api-models.test.ts.snap
src/__tests__/gen-api-models.test.ts
src/commands/gen-api-models/cli.ts
src/commands/gen-api-models/index.ts
src/commands/gen-api-models/types.ts
src/commands/gen-api-sdk/cli.ts
src/commands/gen-api-sdk/index.ts
src/commands/gen-api-sdk/types.ts
src/lib/templating/filters.ts
templates/macros.njk
templates/model.ts.njk

Implements in v5 the changes introduced in PRs #182, #183 and #184

[#174334444] Import latest changes from v4

---

src/__tests__/__snapshots__/gen-api-models.test.ts.snap
templates/client.ts.njk

Removed unused imports from client template

[#174379881] Remove unused imports

---

e2e/src/setup.ts
e2e/yarn.lock

[#174706105] Fix e2e scripts

---

package.json
yarn.lock

this should get rid of our fork of agentkeepalive

[#176012064] Update io-ts-commons

---

README.md
e2e/README.md
e2e/package.json
e2e/src/setup.ts
e2e/yarn.lock
package.json

Renamed package from _"italia-utils"_ to _"@pagopa/openapi-codegen-ts"_

#176398607 renamed to @pagopa/openapi-codegen-ts

---

PULL_REQUEST_TEMPLATE.md

Add a Pull Request template ton this repository
We produce a large number of PR with poor or no description at all. We may benefit a template to enforce the best practice of having an exhaustive description.
This same PR
Kindly inspired by: https://github.com/stevemao/github-issue-templates/blob/master/questions-answers/PULL_REQUEST_TEMPLATE.md

[#176392795] Add pr template

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
__mocks__/api.yaml
__mocks__/be.yaml
e2e/package.json
e2e/src/__tests__/test-api/client.test.ts
e2e/src/__tests__/test-api/definitions.test.ts
e2e/yarn.lock
package.json
src/commands/gen-api-models/__tests__/__snapshots__/index.test.ts.snap
src/commands/gen-api-models/parse.ts
src/commands/gen-api-models/render.ts
src/commands/gen-api-models/types.ts
templates/client.ts.njk
templates/macros.njk
templates/sdk/package.json.njk
yarn.lock

Update all references to `italia-ts-commons` to `@pagopa/ts-commons`:
* in the generator itself https://github.com/pagopa/io-utils/pull/223/commits/df79922ae22992f4a5b01c83aa0572801d2da3e4
* in rendered code https://github.com/pagopa/io-utils/pull/223/commits/df79922ae22992f4a5b01c83aa0572801d2da3e4
* in e2e tests https://github.com/pagopa/io-utils/pull/223/commits/966b26aa0889b16311cd04ffcbf7c5ac8103bb50
This is needed after https://github.com/pagopa/io-ts-commons/pull/344
unit and e2e tests

[#176415651] update ts commons

---

package.json
yarn.lock

[#IP-325] Upgrade Typescript to v4.3.5

---

CODEOWNERS

* remove `CODEOWNERS` file
We are in the process of reviewing how we enforce a validating review before merge. We are shifting from _owners can validate, anyone can merge_ to _anyone can validate, owners can merge_; branch protection is now held by configuring which group/user can push to `master`

[#IP-369] Remove CODEOWNERS

---

__mocks__/api.yaml
e2e/src/__tests__/test-api/client.test.ts
e2e/yarn.lock
src/commands/gen-api-models/__tests__/__snapshots__/index.test.ts.snap
src/commands/gen-api-models/__tests__/index.test.ts
src/commands/gen-api-models/parse.ts
src/commands/gen-api-models/templateEnvironment.ts
templates/client.ts.njk

handle body param in "formData" with "binary" format using `FormData`

[#IC-107] Fix File upload support

---

__mocks__/api.yaml
e2e/src/__tests__/test-api/client.test.ts
e2e/yarn.lock
src/commands/gen-api-models/__tests__/__snapshots__/index.test.ts.snap

After https://github.com/pagopa/io-ts-commons/releases/tag/v10.4.0-RELEASE there are no longer constraints on which header is allowed. We updated e2e tests accordingly.
See commit list

Update e2e tests

---

README.md
src/commands/gen-api-models/__tests__/index.test.ts
src/commands/gen-api-models/parse.v3.ts

The definition of string with a pattern are resolved with a PatternString("{pattern}") in the macro. This will not work with \ character becouse this is also a special caracter for javascript string, so it must be escaped with another \.
reaplce single \ character with \\ in pattern
add unit test 
Use regex with special character wildcard
unit test

Add replace of single \ with \\ for string pattern definition

---

src/commands/gen-api-sdk/index.ts
templates/sdk/.npmignore.njk

`.ts` files in packages are useless at best, and may interfere with project builds at worst. So we don't ship such files when packaging sdk for npm publishing.

[#IC-515] Ignore ts files in package

---

e2e/package.json
e2e/src/__tests__/test-api-v3/client.test.ts
e2e/src/__tests__/test-api/client.test.ts
e2e/src/server.ts
e2e/yarn.lock
src/commands/gen-api-models/__tests__/__snapshots__/index.test.ts.snap
src/commands/gen-api-models/__tests__/parse.test.ts
src/commands/gen-api-models/parse.v2.ts
src/commands/gen-api-models/parse.v3.ts
templates/client.ts.njk

Add support to send body as raw data in the generated client for post,put and patch operations.
e2e test

Add support to raw body in request

---

package.json

Add `io-ts` and `fp-ts` in `peerDependencies`
Include this library in monorepo DX project needs that all the dependencies are declared in `package.json`
not tested

[#DEVEX-60] Add fp-ts and io-ts peerDependencies
