package.json
yarn.lock

npm publish on win32 produces corrupted binaries because of line endings.

fix: npm publish on win32

---

e2e/api.yaml
e2e/be.yaml
e2e/src/__tests__/be/definitions.test.ts
e2e/src/__tests__/be/request-types.test.ts
e2e/src/__tests__/test-api/request-types.test.ts
package.json
src/__tests__/__snapshots__/gen-api-models.test.ts.snap
src/__tests__/api.yaml
src/__tests__/gen-api-models.test.ts
src/gen-api-models/index.ts
templates/client.ts.njk

This PR is inspired by #148 and tries to achieve the same result without losing backward compatibility.
This **is still a draft** because I'd like to write more tests and there are some open questions yet (see below).
Generated response decoders now allow the user to provide a hash set of response decoders in the form _(httpCode, decoder)_. The set may be incomplete and will be filled by defaults. To ensure retrocompatibility, overloads are provided to allow the user to only pass the decoder for the success type (2xx).
Response decoder generation cannot handle the following cases:
* an operation has more than a 2xx type
* an operation which 2xx type returns nothing
The main issue is that actual response decoders allow for only a httpcode-decoder to be overridden (and it's implicitly the …

[#169915207] handle multiple 2xx types in response type generation

---

__mocks__/api.yaml
src/__tests__/__snapshots__/gen-api-models.test.ts.snap

This is just a typo. We didn't see this error before as we never tested on generated file. The functionality works and it's not changed, though.

[#172475116] fix custom import

---

src/__tests__/__snapshots__/gen-api-models.test.ts.snap
templates/client.ts.njk
templates/macros.njk

There was a type error in the generated client. The compiler could not calculate the return type as `testAuthBearerT` _is a private member_ (`testAuthBearerT` is just an example).
> ⚠️ this error isn't caught by our unit/e2e tests, I spotted it once I tried to build a generated sdk by itself. This is probably due to the fact that we use `ts-jest` utility. It's supposed to keep the very same typescript behavior, anyway  It's not the first time it has a slightly different outcome. `ts-jest` is very helpful as it smooths test execution, anyway we should consider the idea of rid it and just build code upfront before tests. 
```typescript
// before
export function Client( /* args */ ): {
readonly testAuthBearer: TypeofApiCall<typeof testAuthBearerT>;
} {
// ...
const testAuthBearerT: …
```

[#172475199] fix client return type

---

README.md
e2e/src/__tests__/be/client.test.ts
e2e/src/__tests__/test-api/client.test.ts
src/__tests__/__snapshots__/gen-api-models.test.ts.snap
templates/client.ts.njk

This is an alternative proposal to #180 .
* `transformEach` are way easier to write
* better type inference
* multiple parameters handled (with exceptions, see _caveats_)
```typescript
import { createClient, DefaultTransformEach } from "my-api/client";
const withBearer: DefaultTransformEach<"Bearer"> = 
wrappedOperation => 
params => { // wrappedOperation and params are correctly inferred
return wrappedOperation({
...params,
Bearer: "VALID_TOKEN"
});
};
//  this is the same of using createClient<"Bearer">. K type is being inferred from withBearer
const { getService } = createClient({
baseUrl: `http://localhost:${mockPort}`,
basePath: "",
fetchApi: (nodeFetch as any) as typeof fetch,
transformEach: withBearer
});
// getService doesn't require "Bearer" anymore, as it's defined in …
```

[#172494831] Wrap operations with default parameters (alternative)

---

templates/macros.njk

Fix string format as https://swagger.io/docs/specification/data-models/data-types/#string

Fix date and date-time format

---

README.md
package.json
src/commands/bundle-api-spec/cli.ts
src/commands/bundle-api-spec/index.ts
src/commands/gen-api-sdk/index.ts
yarn.lock

A utility command to bundle all external references of an API spec into one single file. Plus: bundled spec file is included in the generated SDK.
```sh
$ yarn bundle-api-spec -i /path/to/spec.yaml -o /path/to/bundled-spec.yaml
```

[#174334136] Bundle openapi spec

---

__mocks__/api.yaml
src/__tests__/__snapshots__/gen-api-models.test.ts.snap
src/__tests__/gen-api-models.test.ts
src/commands/gen-api-models/index.ts
src/commands/gen-api-models/types.ts

In developing v5 we lost support for response headers in generated code for type definitions.
For this spec
```yaml
responses:
"201":
description: Request created.
schema:
$ref: "#/definitions/InstanceId"
headers:
Location:
type: string
```
we expected this
```ts
r.IResponseType<201, InstanceId, "Location">
```
but we got this instead
```ts
r.IResponseType<201, InstanceId>
```
Now it's fixed.

[#174379881] Restore support for response header

---

README.md
src/__tests__/gen-api-sdk.test.ts
src/commands/gen-api-sdk/cli.ts
src/commands/gen-api-sdk/index.ts
src/commands/gen-api-sdk/types.ts

Use the `package.json` of the parent application to infer SDK attributes automatically. See [here](https://github.com/pagopa/io-utils/compare/release/5.0.0...174398656-inherit-from-packagejson?expand=1#diff-04c6e90faac2675aa89e2176d2eec7d8R146) for documentation.

[#174398656] Infer SDK package attributes from pacakge.json

---

README.md
__mocks__/api.yaml
e2e/src/__tests__/test-api/definitions.test.ts
src/commands/gen-api-models/__tests__/__snapshots__/index.test.ts.snap
src/commands/gen-api-models/__tests__/index.test.ts
templates/macros.njk

In #182 we fixed generated `WithinRangeInteger`s by including the max number into the set of allowed numbers. It has been reported this may not work, thus I wrote some tests which are passing, instead. 
Incidentally, I'm testing the very same behaviour against `WithinRangeNumber` but I'm getting failures this time. In the end we have now:
* `WithinRangeInteger` to be `[min, max]`
* `WithinRangeNumber` to be `[min, max)`
I wonder if it is the intended behaviour, or instead we need to fix the off-by-one problem in `WithinRangeNumber` as well.

[#174993325] Handle upper bound limit on ranged numbers, integers and strings

---

__mocks__/api.yaml
e2e/src/__tests__/test-api/definitions.test.ts
templates/macros.njk

This PR introduces the management of `exclusiveMaximum` and `exclusiveMinimum`  for integer and number data type.
According to OpenAPI specification, the minimum and maximum values are included in the range and  to exclude the boundary values, is required to specify `exclusiveMinimum: true` and `exclusiveMaximum: true`.
The word “exclusive” in exclusiveMinimum and exclusiveMaximum means the corresponding boundary is excluded:
Keyword | Description
-- | --
exclusiveMinimum: false or not included | value ≥ minimum
exclusiveMinimum: true | value > minimum
exclusiveMaximum: false or not included | value ≤ maximum
exclusiveMaximum: true | value < maximum
**Example**
If we have the following definition:
```yaml
WithinRangeExclusiveMinimumIntegerTest:
title: WithinRangeIntegerTest
type: integer …
```

[#175017856] Handle exclusiveMaximum and exclusiveMinimum 

---

__mocks__/api.yaml
e2e/src/__tests__/test-api/definitions.test.ts
templates/macros.njk

This PR introduces the management of `enum` keyword also for `boolean` type.
This feature is useful for example when you want to define an object in which a property is always true or false:
```yaml
EnumTrueTest:
type: object
properties:
flag:
type: boolean
enum:
- true
```
The definition generated:
```ts
import * as t from "io-ts";
// required attributes
const EnumTrueTestR = t.interface({});
// optional attributes
const EnumTrueTestO = t.partial({
flag: t.literal(true)
});
export const EnumTrueTest = t.exact(
t.intersection([EnumTrueTestR, EnumTrueTestO], "EnumTrueTest")
);
export type EnumTrueTest = t.TypeOf<typeof EnumTrueTest>;
```

[#175498392] Handle enum for boolean type in openapi definition

---

__mocks__/api.yaml
e2e/src/__tests__/test-api/client.test.ts
src/commands/gen-api-models/__tests__/__snapshots__/index.test.ts.snap
templates/client.ts.njk

Remove `safeIdentifier` transformation on query param names, prefer `safeDestruct` instead.
Since auto-generated client parses in query params spec as camelCased properties, we remove this default behavior due to a possible mismatch on query param names that are kebab-based or snake-cased.
Unit tests.

[#176997929] Remove SafeIdentifier on query param names

---

e2e/src/__tests__/test-api/client.test.ts
src/commands/gen-api-models/__tests__/__snapshots__/index.test.ts.snap
templates/client.ts.njk

add wihoutUndefinedValues on QueryParams
Since query params are essentially strings we have to strip out all optional query params that could be possibly undefined. This can solve different issues while dealing with APIs that does not expect query param if they are not defined

Fix withoutUndefinedValues on query params

---

src/commands/gen-api-models/__tests__/__snapshots__/index.test.ts.snap
src/commands/gen-api-models/cli.ts
src/commands/gen-api-sdk/cli.ts
templates/client.ts.njk

Fix `yargs` option type
After upgrading yargs to `"^15.0.1"`,  boolean command options with a default boolean value are not considered while running command.

Fix command args type parsing

---

__mocks__/api.yaml
__mocks__/openapi_v3/api.yaml
src/commands/gen-api-models/__tests__/__snapshots__/index.test.ts.snap
src/commands/gen-api-models/__tests__/parse.test.ts
src/commands/gen-api-models/parse.v2.ts
src/commands/gen-api-models/parse.v3.ts

V11 is generating a `requestTypes.ts` file that is importing a non existing file, when a response $ref is defined within an operation. 
Since we are not currently supporting responses as ref, this PR is to remove response $ref handling.
Bugfixing, V11 introduced a bug that is breaks the build
Unit test, e2e tests

[IOCIT-60]  [Fix] Responses with no schema

---

__mocks__/api.yaml
__mocks__/openapi_v3/api.yaml
e2e/src/__tests__/test-api-v3/client.test.ts
e2e/src/__tests__/test-api/client.test.ts
src/commands/gen-api-models/__tests__/__snapshots__/index.test.ts.snap
src/commands/gen-api-models/__tests__/parse.test.ts
src/commands/gen-api-models/parse.v3.ts

Import the referenced type if the requestBody use a reference
When a requestBody use a reference the referenced type is not imported.
The PR fix the bug importing the referenced type.

Import type if the requestBody use a reference

---

__mocks__/openapi_v3/api.yaml
src/commands/gen-api-models/__tests__/__snapshots__/index.test.ts.snap
src/commands/gen-api-models/__tests__/parse.test.ts
src/commands/gen-api-models/parse.v3.ts

The PR allow to correctly generate header operations parameter from a security schema of type http and scheme bearer
To support security scheme of type http and scheme bearer we convert
If the security schema is defined with type http and scheme bearer like below
```
BearerAuth:
type: http
scheme: bearer
```
the generated operations types do not include the header parameter.
I have added test on parser output and tried to generate the client from an openapi v3 spec.

Support security definition of type http and bearer scheme

---

src/commands/gen-api-sdk/cli.ts
src/commands/gen-api-sdk/index.ts
src/commands/gen-api-sdk/types.ts

* bundle no-strict definitions into the `no-strict` folder
Instead of asking the generator to bundle a package either with strict or no-strict definitions, we prefer to have both kinds in the same package. This is because SDKs are usually generated from servers, while clients have to decide which kind of definitions to adopt.

[#IC-515] Bundle SDK package with `no-strict` definitions

---

__mocks__/api.yaml
__mocks__/openapi_v3/api.yaml
src/commands/gen-api-models/__tests__/parse.test.ts
src/commands/gen-api-models/parse.utils.ts
src/commands/gen-api-models/parse.v2.ts
src/commands/gen-api-models/parse.v3.ts
src/commands/gen-api-models/types.ts

* Infer `type=object` when the definition has properties
* Infer `type=object` when the definition has additional properties
Sometimes users have specifications non-100% compliant and do not specify `type` on definitions. Example: https://github.com/pagopa/pn-commons/blob/develop/docs/openapi/pn-errors.yaml#L67.
In some cases, we can infer the correct type by looking at the other definition fields.

Infer `object` type in definitions when possible

---

__mocks__/api.yaml
__mocks__/openapi_v3/api.yaml
src/commands/gen-api-models/__tests__/__snapshots__/index.test.ts.snap
src/commands/gen-api-models/__tests__/parse.test.ts
src/commands/gen-api-models/parse.v3.ts

see commit list
Parameters in this shape
```YAML
parameters:
- name: param
in: path
required: true
schema:
$ref: "#/components/schemas/CustomDefinition"
```
are now allowed for OpenAPI V3

Handle parameters with `$ref` in schema

---

__mocks__/api.yaml
__mocks__/openapi_v3/api.yaml
src/commands/gen-api-models/__tests__/__snapshots__/index.test.ts.snap
templates/macros.njk

Fix import bug in the generation of a client with headers using parameters with $ref.
Use the generated client with api specs using $ref in typed headers.
e2e test

Remove useless header type in client headers

---

__mocks__/api.yaml
__mocks__/openapi_v3/api.yaml
src/commands/gen-api-models/__tests__/__snapshots__/index.test.ts.snap
templates/macros.njk

- remove `?` from optional header name
- add new openapi v2 and v3 endpoint
- add snaptshots
when there is an optional header, the client is built with a question mark at the end of the header name, causing the build to fail
```
const testHeaderOptionalT: ReplaceRequestParams<
TestHeaderOptionalT,
RequestParams<TestHeaderOptionalT>
> = {
method: \\"get\\",
headers: ({ [\\"param?\\"]: param_ }) => ({
param?: param_
}),
response_decoder: testHeaderOptionalDefaultDecoder(),
url: ({}) => \`\${basePath}/test-header-optional\`,
query: () => withoutUndefinedValues({})
};
```
Unit test

fix: remove `?` from optional header name

---

src/commands/gen-api-models/__tests__/render.test.ts
src/commands/gen-api-models/render.ts

Now `renderDecoderCode`, if no `2xx` response is found, checks for responses with status codes starting with "3" (indicating redirection).
The `gen-api-models` command expects each endpoint to have at least one successful (`2xx`) response - this is not always true, because some endpoints can returns a redirection response (`3xx`) on success.
Unit test

[BREAKING CHANGE:  [IOCOM-1891] Use 3xx responses as success type fallback
